### ISSUE TITLE
How to train person-detection-action-recognition-0006

### ISSUE THREAD

**Issue by Deep-learning999** [open-edge-platform/training_extensions#1041]
I want to train person-detection-action-recognition-0006
Where can I download the training data set of this model? Can you demonstrate the specific process and command line?

**Comment by brmarkus** [comment]
I fear it is trained internally only and might not be shared.

Not using the same mechanisms... but you might find this helpful: "https://github.com/spmallick/learnopencv/tree/master/Human-Action-Recognition-Using-Detectron2-And-Lstm"
