### ISSUE TITLE
 AttributeError: Caught AttributeError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by paularamo** [open-edge-platform/training_extensions#1061]
I am testing how can I create my own model with OTE. I have organized my dataset, So I have a images folder and one single file for annotations in COCO format. I already have the configuration ready and train.py notebook is working well. 

When I change the dataset and I try to run this cell

![Screenshot from 2022-04-15 11-06-00](https://user-images.githubusercontent.com/10940214/163587269-a7fe5fed-8f85-4c82-a28d-6a09276b59a4.png)

I got this error.

![Screenshot from 2022-04-15 11-07-06](https://user-images.githubusercontent.com/10940214/163587359-cb817a76-2a7e-41fe-8fe6-3dffad0aa617.png)
![Screenshot from 2022-04-15 11-07-42](https://user-images.githubusercontent.com/10940214/163587419-9e873f3c-17b9-455b-9912-76ce108d57b5.png)
![Screenshot from 2022-04-15 11-08-32](https://user-images.githubusercontent.com/10940214/163587513-a071fa0f-d6f2-4d88-823a-ae47ff21058f.png)
![Screenshot from 2022-04-15 11-09-21](https://user-images.githubusercontent.com/10940214/163587595-f46e17ae-e4cb-4bcd-9ab1-84e2b5a0ca5b.png)
![Screenshot from 2022-04-15 11-09-48](https://user-images.githubusercontent.com/10940214/163587628-9760c11c-106c-4756-a10c-05d6a0864e3f.png)

Thanks. Appreciate your help on that.

**Comment by eugene123tw** [comment]
@paularamo Could you share what you have changed in the notebook?

**Comment by eugene123tw** [comment]
issue solved
