### ISSUE TITLE
New installation two errors?

### ISSUE THREAD

**Issue by DaveBGld** [open-edge-platform/training_extensions#1092]
Following instructions from [quick start guide](https://github.com/openvinotoolkit/training_extensions/blob/develop/QUICK_START_GUIDE.md), did the following:
`git clone https://github.com/openvinotoolkit/training_extensions.git
```cd training_extensions
git clone https://github.com/openvinotoolkit/training_extensions.git
cd training_extensions
git checkout -b develop origin/develop
```
The last line results in error:

> **fatal: A branch named 'develop' already exists**

I still went ahead and run 

`git submodule update --init --recursive`

>  git submodule update --init --recursive
> Submodule 'external/deep-object-reid' (https://github.com/openvinotoolkit/deep-object-reid) registered for path 'external/deep-object-reid/submodule'
> Submodule 'external/mmdetection' (https://github.com/openvinotoolkit/mmdetection) registered for path 'external/mmdetection/submodule'
> Submodule 'external/mmsegmentation' (https://github.com/openvinotoolkit/mmsegmentation) registered for path 'external/mmsegmentation/submodule'
> Submodule 'external/model-preparation-algorithm/submodule' (https://github.com/openvinotoolkit/model_preparation_algorithm) registered for path 'external/model-preparation-algorithm/submodule'
> Cloning into '/home/david/Downloads/training_extensions/external/deep-object-reid/submodule'...
> Cloning into '/home/david/Downloads/training_extensions/external/mmdetection/submodule'...
> Cloning into '/home/david/Downloads/training_extensions/external/mmsegmentation/submodule'...
> Cloning into '/home/david/Downloads/training_extensions/external/model-preparation-algorithm/submodule'...
> Submodule path 'external/deep-object-reid/submodule': checked out '8376d3ec0d3ceaf540020a070661739cddd9110b'
> Submodule path 'external/mmdetection/submodule': checked out 'ca19197237ab5ecb7e7a27514bd4f464f6d379a6'
> Submodule path 'external/mmsegmentation/submodule': checked out '571a0d38069588787916c682d94888614352972b'
> Submodule path 'external/model-preparation-algorithm/submodule': checked out '8d36bf5944837b7a3d22fc2c3a4cb93423619fc2'

Then after 

`find external/ -name init_venv.sh`

and

```
TASK_ALGO_DIR=./external/mmsegmentation/
bash $TASK_ALGO_DIR/init_venv.sh ./cur_task_venv python3.8
source ./cur_task_venv/bin/activate
pip3 install -e ote_cli/ -c $TASK_ALGO_DIR/constraints.txt
````

 And then 
`ote find --root $TASK_ALGO_DIR`

results in error **ModuleNotFoundError: No module named 'ote_sdk'**:

> (segmentation) david@AI01:~/Downloads/training_extensions$ ote find --root $TASK_ALGO_DIR
> Traceback (most recent call last):
>   File "/home/david/Downloads/training_extensions/cur_task_venv/bin/ote", line 11, in <module>
>     load_entry_point('ote-cli', 'console_scripts', 'ote')()
>   File "/home/david/Downloads/training_extensions/cur_task_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/home/david/Downloads/training_extensions/cur_task_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
>     return ep.load()
>   File "/home/david/Downloads/training_extensions/cur_task_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
>     return self.resolve()
>   File "/home/david/Downloads/training_extensions/cur_task_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/home/david/Downloads/training_extensions/ote_cli/ote_cli/tools/ote.py", line 22, in <module>
>     from .demo import main as ote_demo
>   File "/home/david/Downloads/training_extensions/ote_cli/ote_cli/tools/demo.py", line 25, in <module>
>     from ote_sdk.configuration.helper import create
> ModuleNotFoundError: No module named 'ote_sdk'
>

**Comment by JihwanEom** [comment]
Hi @DaveBGld , sorry for late reply.

Could you try 'cd ote_sdk; pip install -e .' in your ote directory?

I think this can be a solution for you.

**Comment by DaveBGld** [comment]
Yes. That did it
