### ISSUE TITLE
where can I find code for "lightweight network architecture for real-time action recognition"?

### ISSUE THREAD

**Issue by poincarelee** [open-edge-platform/training_extensions#1201]
Hi, I am working on real-time video action recognition, and I found your great work "lightweight network architecture for real-time action recognition" , which has got a really  fantastic result "56 fps on CPU". But I cannot find code for it in this repository through the old address, could you give me any clues about it?

**Comment by sovrasov** [comment]
https://github.com/openvinotoolkit/mmaction2

**Comment by sungmanc** [comment]
Close this issue, please reopen it if there is any problem.
