### ISSUE TITLE
Hpopt model not found

### ISSUE THREAD

**Issue by Praveen-24-mvp** [open-edge-platform/training_extensions#1290]
Hi Team , 
 I tried to run the fallowing command.

`ote find --root ./external/mmdetection/` 

But I can't able to fetch the result , because while running it parsing an error like 

**" cannot import hpopt module
[] "**

Assist us to resolve this issue 

Thanks in Advance :smile:

**Comment by bbartling** [comment]
did you ever figure this out?

**Comment by eunwoosh** [comment]
Sorry for late reply. I try to reproduce this issue, but I can't. Could you explain your installation method and your environment?

**Comment by eunwoosh** [comment]
Anyway, you can solve this issue manually by installing package. please follow bellow command

1. git clone https://github.com/openvinotoolkit/hyper_parameter_optimization
2. cd hyper_parameter_optimization
3. pip install .

**Comment by sungmanc** [comment]
Close this issue, please reopen it if there is any problem.
