### ISSUE TITLE
Help to bootstrap the project (begineer)

### ISSUE THREAD

**Issue by bbartling** [open-edge-platform/training_extensions#1336]
Hi,

I got some tips from the Intel community message board:

> Steps to start a custom person detection model training:
> 
> 1. - Follow Steps 1 to 5 in [training_extention documentation](https://github.com/openvinotoolkit/training_extensions/tree/4c85176f611fad2f9c30e11be61a548ba7534db3#misc).
> 2. - Deactivate the virtual environment once completed.
> 3. - Follow Steps 1 to 5 in [person detection documentation](https://github.com/openvinotoolkit/training_extensions/tree/4c85176f611fad2f9c30e11be61a548ba7534db3/models/object_detection/model_templates/person-detection).

In step noted above, am I supposed to clone a particular branch? If I clone per the directions in the [README](https://github.com/openvinotoolkit/training_extensions/tree/4c85176f611fad2f9c30e11be61a548ba7534db3#setup-openvino-training-extensions): 

```
git clone https://github.com/openvinotoolkit/training_extensions.git
export OTE_DIR=`pwd`/training_extensions
```
I think it just gives me the develop branch on my Ubuntu 20.04 machine, this is what I am on:
```
$ git status
On branch develop
Your branch is up to date with 'origin/develop'.
```

On [step 5 ](https://github.com/openvinotoolkit/training_extensions/tree/4c85176f611fad2f9c30e11be61a548ba7534db3#:~:text=install%20ote%20package%3A)further down....on the `develop` branch I cannot complete this step:
`pip3 install -e ote/`

The develop branch I have a `ote_cli` directory and `ote_sdk` directory....will one of these work? If did a `pip install -e` on both.

Also notice the develop branch doesn't have a models directory...thanks for any tips getting me going
![image](https://user-images.githubusercontent.com/29737117/200191995-3a551d41-d7a4-4e7d-8449-6b05140dbf6f.png)

**Comment by JihwanEom** [comment]
Please use our latest develop branch and refer quick start guide. https://github.com/openvinotoolkit/training_extensions/blob/develop/QUICK_START_GUIDE.md

**Comment by bbartling** [comment]
Thank you for the response....am very new to openVINO so any beginner level language/tips greatly appreciated.

On the dev branch quick start link that you provided me I have the `detection` virtual env up and successful [up to the](https://github.com/openvinotoolkit/training_extensions/blob/develop/QUICK_START_GUIDE.md#ote-find) `find ote` step where I run:
`ote find --root $TASK_ALGO_DIR`

But just return empty brackets `[]` is because I don't have any of the pretrained open model zoo models downloaded?

Can I still re-tune an existing pretrained model in the open_model_zoo library, [these steps](https://github.com/openvinotoolkit/training_extensions/tree/4c85176f611fad2f9c30e11be61a548ba7534db3/models/object_detection/model_templates/person-detection#a-prepare-dataset) with the `people detection 2020`.

I have a data set prepared on my machine of a directory of jpeg images of people which I am hoping to try out.

Also curious on the `ote train` do I need to come up with my own `label_schema.json` if I am using my own dataset or is that something already built into the `people detection 2020` even if I use my own dataset?

**Comment by bbartling** [comment]
Regarding the image annotation statement that I asked above (the `label_schema.json`) I used this tool called [labelImg](https://github.com/heartexlabs/labelImg) which generates an XML file for each image.


Looks like this:
![image](https://user-images.githubusercontent.com/29737117/201537221-eb82fef9-ba75-4b76-b5e8-316e2e1c82d8.png)


Just curious if this is something I can use to retrain an existing pretrained open_model_zoo model but could use some help getting started.

**Comment by bbartling** [comment]
Im getting further help here:

https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/openVINO-extensions-retrain-a-model/m-p/1430808#M28650
