### ISSUE TITLE
TargetDevice selection

### ISSUE THREAD

**Issue by paularamo** [open-edge-platform/training_extensions#1350]
How can I define the target device using ote_sdk? I saw model_template.py. Could you please give me an example if I would like to use my second GPU? or run AUTO?
![image](https://user-images.githubusercontent.com/10940214/200887426-03da0dc8-a500-4565-8cda-c53c5e2bec46.png)

Maybe @eugene123tw , could you please help me with that? :)

Thanks and Kind regards

**Comment by eugene123tw** [comment]
Currently, we don't expose this option to the users directly. That being said, we will be supporting a device arg in [demo.py](https://github.com/openvinotoolkit/training_extensions/blob/develop/ote_sdk/ote_sdk/usecases/exportable_code/demo/demo.py), so in the future, you can run inference on a specific device.

**Comment by paularamo** [comment]
Thanks @eugene123tw .
