### ISSUE TITLE
Not able to run ote train 

### ISSUE THREAD

**Issue by kenilaivid** [open-edge-platform/training_extensions#1434]
I have followed all steps to install and run ote commands using this [link](https://github.com/openvinotoolkit/training_extensions/blob/develop/QUICK_START_GUIDE.md) 

First error while running this command and making environment 
`external/model-preparation-algorithm/init_venv.sh .venv_mpa`
![image](https://user-images.githubusercontent.com/117429458/207018794-2ffd11d1-23e6-49a4-aca1-5f9b52808931.png)
Which can be the best version of python (current version is python 3.7)  and openvino (current version is openvino 2021.1.110) to avoid this dependency error. 

Secondly, I get a error when I run this command  `ote train external/model-preparation-algorithm/configs/detection/cspdarknet_yolox_cls_incr/template.yaml --train-ann-file /home/citrus/Desktop/kenil/Vehicle_Detection/train.csv  --train-data-roots /home/citrus/Desktop/kenil/Vehicle_Detection/train/ --val-ann-files /home/citrus/Desktop/kenil/Vehicle_Detection/val.csv --val-data-roots /home/citrus/Desktop/kenil/Vehicle_Detection/validation/ --save-model-to outputs`

![image](https://user-images.githubusercontent.com/117429458/207022548-448b092b-92a7-4ddb-8e14-a2d5ae031e09.png)

Kindly, tell me the solutions to problems.

**Comment by JihwanEom** [comment]
Hello, sorry for late reply.

There was many changes for this repository. Could you try to install OTX on latest develop branch with quick start guide?
(https://github.com/openvinotoolkit/training_extensions/blob/develop/QUICK_START_GUIDE.md)

**Comment by sungmanc** [comment]
Close this issue, please reopen it if there is any problem.
