### ISSUE TITLE
numpy version

### ISSUE THREAD

**Issue by VicencPB** [open-edge-platform/training_extensions#1577]
Hello,  I have installed OTE without problems, on Ubuntu Ubuntu 20.04.5 LTS,  following the instructions at:

https://github.com/openvinotoolkit/training_extensions/blob/master/QUICK_START_GUIDE.md

But when I try to use any command, it appears an error related to the numpy version:

~/software/training_extensions$ ote
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.17.4 (/usr/lib/python3/dist-packages), Requirement.parse('numpy<1.27.0,>=1.19.5'), {'scipy'})

I would appreciate any help to solve this issue.

Thank you very much

**Comment by goodsong81** [comment]
Hello,
The `master` branch had been deprecated long ago. Would you try `develop` branch?### https://github.com/openvinotoolkit/training_extensions/blob/develop/QUICK_START_GUIDE.md

**Comment by sungmanc** [comment]
Close this issue, please reopen it if there is any problem.
