### ISSUE TITLE
OTX CLI details are missing

### ISSUE THREAD

**Issue by daniil-lyakhov** [open-edge-platform/training_extensions#1634]
In page https://github.com/openvinotoolkit/training_extensions/tree/develop/otx/cli

links with details (`here`) as well as link to Face detection notebook are broken
![image](https://user-images.githubusercontent.com/74656388/217035073-f5ea56cd-31cd-433e-85c7-889f54024a7f.png)

**Comment by goodsong81** [comment]
The page had been removed. CLI details are in README.me & QUICK_START_GUIDE.md in the project root.
Thank you for the reporting!
