### ISSUE TITLE
OpenVINO 2022.1 support (for MyriadX targets)

### ISSUE THREAD

**Issue by QSmally** [open-edge-platform/training_extensions#2063]
Currently the training extensions support `openvino==2022.3.0` and alike, however, 2022.3 removed Myriad support. Is there a way to train a model for OpenVINO 2022.1 which still supports the Myriad VPU without going back to an earlier commit of this repository?

I trained an OpenVINO 2022.3 model, but upon converting it to a `MyriadX blob`, I was confronted with the exception `Cannot create NonMaxSuppression layer /NonMaxSuppression id:2331 from unsupported opset: opset9` with the blobconverter tool.

Or else, how do you recommend training an SSD/ATSS model with a COCO dataset through OpenVINO 2022.1?

**Comment by goodsong81** [comment]
OpenVINO is not involved in training but export. Would you try `otx export` after downgrading the OpenVINO version by `pip install openvino==2022.1 openvino-dev==2022.1`? There might be some argument mismatch, @sovrasov might be able to help you in that case.
