### ISSUE TITLE
otx build can not recognize template when templates are lower case.

### ISSUE THREAD

**Issue by jaegukhyun** [open-edge-platform/training_extensions#2066]
**Describe the bug**
When otx workspace is built with lower case template(e.g. yolox), otx cannot recognize template.

**Steps to Reproduce**

1. otx build yolox --train-data-roots {train_roots} --val
-data-roots {val_roots} --workspace otx-workspace-yolox
2. otx build YOLOX --train-data-roots {train_roots} --val
-data-roots {val_roots} --workspace otx-workspace-yolox

Log for step 1.
/local/jaeguk/otx/venv/otx/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
[*] Detected dataset format: voc
[*] Detected task type: DETECTION
[*] Workspace Path: otx-workspace/experiments/yolox/voc
[*] Load Model Template ID: Custom_Object_Detection_Gen3_ATSS
[*] Load Model Name: ATSS

Log for step 2.
/local/jaeguk/otx/venv/otx/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
[*] Workspace Path: otx-workspace/experiments/yolox/voc
[*] Load Model Template ID: Custom_Object_Detection_YOLOX
[*] Load Model Name: YOLOX

**Environment:**

- OS: 
- Framework version: 
- Python version:
- OpenVINO version:
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by harimkang** [comment]
I will fix this bug before the 1.3.0 release.

**Comment by harimkang** [comment]
Resolve this bug in the corresponding PR (https://github.com/openvinotoolkit/training_extensions/pull/2121).
