### ISSUE TITLE
E2E tests FAILED when tested with CUDA_VISIBLE_DEVICES option

### ISSUE THREAD

**Issue by sungmanc** [open-edge-platform/training_extensions#2070]
**Describe the bug**

* When I was executing E2E tests with CUDA_VISIBLE_DEVICES=0,1 options, E2E tests fails.
![image](https://user-images.githubusercontent.com/80735344/234446042-6a64a6f5-0625-4571-bfc9-4db75c513c21.png)
![image](https://user-images.githubusercontent.com/80735344/234446128-d5a569cc-37d3-4d1f-abfc-59015e452cb0.png)

* It seems that there are mis-configuration setting.

**Steps to Reproduce**

1.CUDA_VISIBLE_DEVICES=0,1 tox -e pre-merge-all-py310 -- -s -x tests/e2e/cli

**Environment:**

- OS: Ubuntu 20.04
- Framework version: OTX 1.2 develop branch
- Python version: python 3.10
- CUDA/cuDNN version: 11.7

**Comment by eunwoosh** [comment]
Bug is fixed
