### ISSUE TITLE
Missing CONTRIBUTING.md file

### ISSUE THREAD

**Issue by leoll2** [open-edge-platform/training_extensions#2092]
**Describe the bug**

The [pull request template](https://raw.githubusercontent.com/openvinotoolkit/training_extensions/develop/.github/pull_request_template.md) contains a dead link to non-existing [CONTRIBUTING.md](https://github.com/openvinotoolkit/training_extensions/blob/develop/CONTRIBUTING.md). I can't find such a file anywhere in the repo, maybe it'd be a good idea to recreate it?

**Comment by sungmanc** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/2128
