### ISSUE TITLE
OSError and ValueError are output, but the test passes.

### ISSUE THREAD

**Issue by harimkang** [open-edge-platform/training_extensions#2104]
**Describe the bug**
The following log is output, but the test passes.
![image](https://user-images.githubusercontent.com/38045080/235857388-b7e9cea0-464c-4707-95c1-163b14c47cbb.png)
Logs found in multiple test cases, only found in CI.

https://pipelines.actions.githubusercontent.com/serviceHosts/00bf99cf-6dc0-46f5-bd23-cec989dd8df0/_apis/pipelines/1/runs/10668/signedlogcontent/49?urlExpires=2023-05-03T05%3A24%3A09.0365915Z&urlSigningMethod=HMACV1&urlSignature=x50sTvCyk7qNqPJz%2FSU1OLvbAGs0%2FvQY61qZ0x5%2F1Ck%3D

**Steps to Reproduce**

1. Run Integration Test in CI
2.
3.
4.

**Environment:**

https://github.com/openvinotoolkit/training_extensions/actions/runs/4867038603/jobs/8679731520

**Comment by sungmanc** [comment]
If this issue only occurred in CI, please assign @yunchu  for this issue.

**Comment by yunchu** [comment]
the issue is not observed currently. please reopen when it happened again.
