### ISSUE TITLE
Action Classification loads weird checkpoint

### ISSUE THREAD

**Issue by sungmanc** [open-edge-platform/training_extensions#2118]
**Describe the bug**

Training goes well, however, in the evaluation phase, OTX loads the weird checkpoint.
In the figure below, OTX loads the 1 epoch's checkpoint although OTX already had better checkpoints.
(10 epoch's result: 0.72, 1 epoch's result: 0.04)

![image](https://user-images.githubusercontent.com/80735344/236867678-a253e166-03d8-436a-b373-5b52e031355e.png)

**Steps to Reproduce**

1. tox -e weekly-test

**Environment:**

- OS:  Ubuntu20.04
- Framework version:  Pytorch1.13.1
- Python version: 3.10
- OpenVINO version: 2022.03
- CUDA version: 10.7

**Comment by jaegukhyun** [comment]
Thanks for the report, I'll look into it

**Comment by jaegukhyun** [comment]
Solved by **https://github.com/openvinotoolkit/training_extensions/pull/2132**
