### ISSUE TITLE
How can the input size be adjusted?

### ISSUE THREAD

**Issue by cansik** [open-edge-platform/training_extensions#2166]
I trained a YOLOX based object detection with very small objects and it seems that the current input size (`416x416`) is not enough to detect the small objects. How is it possible to change the input size during training **and** deployment (e.g. `640x640`)?

For deployment I found the `model_inputs` parameter inside the `deployment.py`, but how to adjust the sizes for training as well? There is the `data_pipeline.py` which contains different values for training and testing. Does that mean training is done with `640` and testing with `416`? And than there is the `tile_pipeline.py` which again has different values for the moasic (I guess)?

What I would like to have is a single parameter to set the image size, instead of having to adjust all transformations manually inside the different pipelines. Is something like that possible, or where would you adjust the size to be able to train and test with `640`?

**Comment by harimkang** [comment]
Hi @cansik,
In fact, we don't yet support changing the `input_size` from the CLI, but we may add that feature in the future.
I think for now (for the default trainig) you can just change all the `img_scales` in `data_pipeline.py`. 

and,
We're actually providing something called tiling detection for small objects. (`tile_pipeline.py` is used in this case.)
This can be enabled by adding the command `params --tiling_parameters.enable_tiling` or by modifying `enable_tiling` in `tiling_parameters` to `true` in `configuration.yaml`. (with tiling, You get better accuracy for small objects, but this can be slower than basic training.)

@jaegukhyun @goodsong81 Let me know if you'd like to add to my comments or fix anything. + 
Please provide additional comments on the questions in this issue.

**Comment by jaegukhyun** [comment]
Hi @cansik 
As harim said, to modify input size of image, you should modify data_pipeline.py in your otx-workspace.
![image](https://github.com/openvinotoolkit/training_extensions/assets/106788349/b69874e9-f5bd-42d9-afcc-e37d0c4da230)
As you can see in the data_pipeline.py YOLOX is trained by 640 * 640 image and evaluated by 416 * 416 image. You can enlarge both training and validation input image via modifying these values.
In addition you can export model with new modified input size via modifying model input value in deployment.py in your otx-workspace
![image](https://github.com/openvinotoolkit/training_extensions/assets/106788349/c47b7214-c552-410d-8205-153a5029fe6e)

Also, OTX provide tiling feature for small object detection. You can run tiling with otx train --workspace {YOUR WORKSPACE} params --tiling_parameters.enable_tiling true
Tiling increases small object detection performance through dividing image to small tiles and train with enlarged tile. I believe this feature might help you.

**Comment by cansik** [comment]
Thank you both for the good answers. Tiling did not work in my case, I always get and an AP of 0. Maybe I would have to change the titling parameters.
