### ISSUE TITLE
E2E test is stuck while testing HPO with i-seg tiling tasks

### ISSUE THREAD

**Issue by eunwoosh** [open-edge-platform/training_extensions#2167]
**Describe the bug**

E2E test is stuck while testing HPO with i-seg tiling tasks.

**Steps to Reproduce**

1. setup OTX
2. go to OTX base directory
3. pytest tests/e2e/cli/instance_segmentation/test_tiling_instseg.py::TestToolsTilingInstanceSegmentation::test_otx_hpo

**Environment:**

- OS: Ubuntu 20.04 
- Framework version: 1.13.1 
- Python version: 3.10
- OpenVINO version: 2022.3.0
- CUDA/cuDNN version: 11.7
- GPU model and memory: RTX3090

**Comment by eunwoosh** [comment]
After #2175 is merged and check tests, I'll enable tests.

**Comment by sungmanc** [comment]
@eunwoosh , is it done? If so, how about closing this issue?

**Comment by eunwoosh** [comment]
Thanks for notifying.

> @eunwoosh , is it done? If so, how about closing this issue?
