### ISSUE TITLE
No regression test of SupCon for semantic segmentation

### ISSUE THREAD

**Issue by sungchul1** [open-edge-platform/training_extensions#2171]
**Describe the bug**

There is no regression test of SupCon for semantic segmentation, so when there are some changes in recipes, comparing previous and current recipes is impossible.

**Steps to Reproduce**

1.
2.
3.
4.

**Environment:**

- OS: 
- Framework version: 
- Python version:
- OpenVINO version:
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by sungmanc** [comment]
@sungchul2 , there is no `supcon` folder in the `lite HRNet-18` (checked from @harimkang). Is there any reason?

**Comment by sungchul1** [comment]
I heard that `lite HRNet-18` would be deprecated and supcon for `lite HRNet-18` was not needed.
But if needed it can be created.

**Comment by sungmanc** [comment]
> I heard that `lite HRNet-18` would be deprecated and supcon for `lite HRNet-18` was not needed. But if needed it can be created.

In the current status, we need that template. So, could you make one?

**Comment by sungmanc** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/2177
