### ISSUE TITLE
Anomaly task sometimes show large performance drop before and after export, optimize, deploy

### ISSUE THREAD

**Issue by jaegukhyun** [open-edge-platform/training_extensions#2189]
**Describe the bug**
In regression task, some category of mvtec dataset shows large performance drop before and after export, optimize, deploy

**Steps to Reproduce**

1. Run regression test
2.
3.
4.

**Environment:**

- OS: 
- Framework version: 
- Python version:
- OpenVINO version:
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by jaegukhyun** [comment]
@ashwinvaidya17 Any update?

**Comment by ashwinvaidya17** [comment]
@jaegukhyun unfortunately there has been no update. We are currently working on updating the model export and integrating the pre/post-processing steps in the model graph. But this issue i s on our agenda as it affects anomalib as well.
