### ISSUE TITLE
Sporadic failure of tiling max annotation unit test

### ISSUE THREAD

**Issue by sovrasov** [open-edge-platform/training_extensions#2245]
PR: https://github.com/openvinotoolkit/training_extensions/pull/2243
Run: https://github.com/openvinotoolkit/training_extensions/actions/runs/5268671825/jobs/9525692994?pr=2243

Failure in UT py 3.10 (also observed on other PRs):
FAILED tests/unit/algorithms/detection/tiling/test_tiling_detection.py::TestTilingDetection::test_max_annotation

Locally not reproduced (py 3.8 and 3.10)

**Comment by sungmanc** [comment]
@eugene123tw, could you take a look?

**Comment by yunchu** [comment]
same issue was happened here https://github.com/openvinotoolkit/training_extensions/actions/runs/5515301227/jobs/10055663517?pr=2331

**Comment by eugene123tw** [comment]
@yunchu We skipped it, could you rebase the branch: https://github.com/openvinotoolkit/training_extensions/blob/develop/tests/unit/algorithms/detection/tiling/test_tiling_detection.py#L377
