### ISSUE TITLE
otx eval error : Can't find the argument 'train_data_roots'

### ISSUE THREAD

**Issue by raushani2v** [open-edge-platform/training_extensions#2250]
Hi, I am getting following error while executing otx eval command :

   File "/usr/local/lib/python3.8/dist-packages/otx/cli/manager/config_manager.py", line 173, in configure_template
        raise ConfigValueError("Can't find the argument 'train_data_roots'")
  otx.cli.utils.errors.ConfigValueError: Can't find the argument 'train_data_roots'

**eval** command that I am using is:

otx  eval  --test-data-roots /home/TrainingData/readyToTrain/test --load-weights /home/training_extensions/external/deep-object-reid/configs/models/weights.pth --output /home/training_extensions/external/deep-object-reid/configs/models

**Comment by harimkang** [comment]
Hi @raushani2v, thank you for reporting a case where sending out inappropriate messages. I'll fix it quickly.

However, i have one question, did you run your command from inside the workspace? 
If not, putting the model's template path in the command might work just fine. (Make sure to include the template that generated model weight in the eval as well.)
```
otx eval {model_template_path} -test-data-roots /home/TrainingData/readyToTrain/test --load-weights /home/training_extensions/external/deep-object-reid/configs/models/weights.pth --output /home/training_extensions/external/deep-object-reid/configs/models
```

Could you please try the above?
Thanks for the report and have a great day.

**Comment by harimkang** [comment]
My guess is that the merge of this PR (https://github.com/openvinotoolkit/training_extensions/pull/2251) should have resolved the issue.
Could you please double check and close it?

**Comment by raushani2v** [comment]
Hi @harimkang, Now the command is working fine from inside the workspace. Thank you
