### ISSUE TITLE
Large accuracy drop on Custom_Image_Classification_EfficientNet-V2-S with 2 GPUs

### ISSUE THREAD

**Issue by yunchu** [open-edge-platform/training_extensions#2253]
**Describe the bug**

while running regression testing, I can observe the large accuracy drop on Custom_Image_Classification_EfficientNet-V2-S.
evaluation score = 0.11111111
```bash
FAILED tests/regression/classification/test_classification.py::TestRegressionMultiClassClassification::test_otx_train[Custom_Image_Classification_EfficientNet-V2-S] - AssertionError: Performance: (0.1111111111111111) < Criteria: (0.6948)
```

**Steps to Reproduce**

1. prepare test datasets
2. CI_DATA_ROOT=/mnt/hdd1/data/ci_datasets tox -e tests-all-py310 -- tests/regression/classification/test_classification.py::TestRegressionMultiClassClassification::test_otx_train[Custom_Image_Classification_EfficientNet-V2-S]

**Environment:**

- OS: ubuntu 20.04
- Framework version: using tox
- Python version: 3.10
- OpenVINO version: using tox
- CUDA/cuDNN version: 11.7.1
- GPU model and memory: RTX3090 / 24G

**Comment by antaru-ops** [comment]
I have faced something similar. I need some explanation for this too. 

I have trained a flower dataset with Custom_Image_Classification_MobileNet-V3-large-1x. The performance score of the model is about 0.9673.
![image](https://github.com/openvinotoolkit/training_extensions/assets/73929070/4b5299f0-41eb-4500-a817-b30f922767c9)
After I optimize it with nncf, the performance score drops to 0.1730
![image](https://github.com/openvinotoolkit/training_extensions/assets/73929070/2e37639f-7712-45e9-8563-2ff20df820c4)

Environment: Ubuntu 22.04
Python Version: 3.10
GPU: 2 x RTX3060
