### ISSUE TITLE
CUDA out of memory on RTX3060

### ISSUE THREAD

**Issue by antaru-ops** [open-edge-platform/training_extensions#2260]
Hi, I'm trying to optimize my model for instance segmentation, however it keeps showing that CUDA is out of memory for twice already. I have two gpus RTX3060 and for optimization I think only one of them is being used. I am wondering if there's any parameters that I can adjust to utilize both GPUs during optimization or adjusting the value of other parameters to avoid this issue? 

1st time error. Command: otx optimize --load-weights outputs/latest_trained_model/models/weights.pth --train-data-roots splitted_dataset/train/ --val-data-roots splitted_dataset/val/

![Screenshot from 2023-06-22 23-23-03](https://github.com/openvinotoolkit/training_extensions/assets/73929070/fc075e27-b1a8-42c5-b3c0-b378edc7da0e)

2nd time error. Command: otx optimize
![Screenshot from 2023-06-22 23-22-34](https://github.com/openvinotoolkit/training_extensions/assets/73929070/6e3faa70-b0ee-44d3-adda-ab073250c89a)

Environment
OS: Ubuntu 22.04
GPU: NVIDIA RTX3060
CUDA: 11.7

**Comment by sungmanc** [comment]
@antaru-ops , we don't support the multi-GPU optimization now. If this issue occurred by the GPU memory itself, then could you make lower batch size for your training & optimization? 

@sovrasov any other idea / comments ?

**Comment by sovrasov** [comment]
NNCF optimization is currently doesn't support FP16 training due to NNCF internal limitations, so it requires more memory than training, which is conducted in FP16 mode. FP16 support is WIP from the NNCF side.
The only way to reduce GPU memory usage now is decreasing the batch size.

**Comment by antaru-ops** [comment]
I see. Noted with thanks :)
