### ISSUE TITLE
Failures on Custom_Counting_Instance_Segmentation_MaskRCNN_ConvNeXt with POT/PTQ 

### ISSUE THREAD

**Issue by eugene123tw** [open-edge-platform/training_extensions#2298]
**Describe the bug**

otx optimize.py failed on ConvNeXt OpenVINO model.

POT failure on ConvNeXt model

![image](https://github.com/openvinotoolkit/training_extensions/assets/13793254/5e107754-6b33-4f28-9116-5f471caf46fa)

PQT still raise error after merging Vlad's latest PR:
![image](https://github.com/openvinotoolkit/training_extensions/assets/13793254/3cd67ee3-6bd9-4bc2-8f37-12ada61e293c)

**Steps to Reproduce**

1. Check out https://github.com/eugene123tw/training_extensions/tree/eugene/CVS-109844-new-inst-segm-model
2. `otx export src/otx/algorithms/detection/configs/instance_segmentation/convnext_maskrcnn/template.yaml --load-weights weights.pth`
3. `otx optimize src/otx/algorithms/detection/configs/instance_segmentation/convnext_maskrcnn/template.yaml --train-data-roots tests/assets/car_tree_bug --val-data-roots tests/assets/car_tree_bug --load-weights openvino.xml`

**Environment:**

- OS: Linux Ubuntu 20.04
- Framework version: PyTorch 1.13.1
- Python version: 3.10
- OpenVINO version: 2022.3 and 2023.0
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by sovrasov** [comment]
Nor POT or PTQ use model wrappers at the quantization step. From the second screenshot I see that PTQ stage is likely to be finished sucsessfully.

Current POT pipeline is: bare .xml FP32 model -> POT/PTQ (MAPI wrapper is not used) -> INT8 .xml model -> eval with MaskRCNN wrapper

@eugene123tw are you sure that the failure occurs at the POT stage? Could you elaborate a bit? Is standalone call of otx eval successful with the source FP32 .xml?

**Comment by wonjuleee** [comment]
The error `data.size() == OC` looks like coming from post operation composer as shown below.
https://github.com/openvinotoolkit/openvino/blob/642c69115d3a212ec920a6413c9f5b5b61d8ad94/src/plugins/intel_cpu/src/dnnl_postops_composer.cpp#L85
And this may be raised when the eltwise prelu layer contains multiple scale values (more than 1). Please refer to https://github.com/openvinotoolkit/openvino/blob/642c69115d3a212ec920a6413c9f5b5b61d8ad94/src/plugins/intel_cpu/src/nodes/eltwise.cpp#L2656.
Could you check the model contains any related layer, which requires a single scale but contains multiple scales in a model?

**Comment by eugene123tw** [comment]
> Nor POT or PTQ use model wrappers at the quantization step. From the second screenshot I see that PTQ stage is likely to be finished sucsessfully.
> 
> Current POT pipeline is: bare .xml FP32 model -> POT/PTQ (MAPI wrapper is not used) -> INT8 .xml model -> eval with MaskRCNN wrapper
> 
> @eugene123tw are you sure that the failure occurs at the POT stage? Could you elaborate a bit? Is standalone call of otx eval successful with the source FP32 .xml?

Before optmiziation finishes, it loads back the inferencer. So I guess, it only ran half-way. 
![image](https://github.com/openvinotoolkit/training_extensions/assets/13793254/f123bf97-bda9-4d50-ba16-cb26f356ee5b)

**Comment by eugene123tw** [comment]
> The error `data.size() == OC` looks like coming from post operation composer as shown below. https://github.com/openvinotoolkit/openvino/blob/642c69115d3a212ec920a6413c9f5b5b61d8ad94/src/plugins/intel_cpu/src/dnnl_postops_composer.cpp#L85 And this may be raised when the eltwise prelu layer contains multiple scale values (more than 1). Please refer to https://github.com/openvinotoolkit/openvino/blob/642c69115d3a212ec920a6413c9f5b5b61d8ad94/src/plugins/intel_cpu/src/nodes/eltwise.cpp#L2656. Could you check the model contains any related layer, which requires a single scale but contains multiple scales in a model?

@wonjuleee It uses 2 kinds of nonlinear layers relu and gelu and does not contain any prelu layers. Could you take a look?

**Comment by eugene123tw** [comment]
Issue fixed in CVS-118373. Fixed will be released in OpenVINO 2023.2
