### ISSUE TITLE
Randomly fails on: TestExplainMethods::test_saliency_map_det

### ISSUE THREAD

**Issue by sungmanc** [open-edge-platform/training_extensions#2330]
**Describe the bug**

When I checked the results of the unit tests, I got results below
![image](https://github.com/openvinotoolkit/training_extensions/assets/80735344/c90c9c10-7545-4649-bc36-15753364d1b6)

![image](https://github.com/openvinotoolkit/training_extensions/assets/80735344/42515598-3791-4ac8-9f67-6f4db63b78d4)

The failure occurs at TestExplainMethods::test_saliency_map_det[SSD]. It didn't occur at Python3.8 unit tests. So, randomly happened.

**Steps to Reproduce**

1. Using the CI tests

**Comment by negvet** [comment]
The fix is already in the 1.4.0 branch https://github.com/openvinotoolkit/training_extensions/pull/2322/commits/85317ab18a22991c3510dba1254e0b1b6940b132. In the meantime, cherry-pick it into the develop as well https://github.com/openvinotoolkit/training_extensions/pull/2338

**Comment by sungmanc** [comment]
> The fix is already in the 1.4.0 branch [85317ab](https://github.com/openvinotoolkit/training_extensions/commit/85317ab18a22991c3510dba1254e0b1b6940b132). In the meantime, cherry-pick it into the develop as well #2338

Got it, thanks !

**Comment by sungmanc** [comment]
It seems that the issue still exists, could you take a look?
![image](https://github.com/openvinotoolkit/training_extensions/assets/80735344/927e5921-28da-4ed0-b0b8-8af5b58e4f5e)

It happens at https://github.com/openvinotoolkit/training_extensions/pull/2342

**Comment by negvet** [comment]
Thanks for letting me know. But I need to see how the error looks like, cannot find it in the current open PR checks (cannot reproduce it locally)

**Comment by sungmanc** [comment]
@negvet , If we re-run the CI, the issue is gone. That's the reason why we couldn't find the FAILED PR. Same error occurred at https://github.com/openvinotoolkit/training_extensions/pull/2352, I attached the detailed log.
![image](https://github.com/openvinotoolkit/training_extensions/assets/80735344/8cdb8bd6-9ab7-409e-8eb7-3b1dcf501b64)
