### ISSUE TITLE
RuntimeError: nms_impl: implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by bismillahkani** [open-edge-platform/training_extensions#2343]
**Describe the bug**

Getting runtime error "implementation for device cuda:0 not found" for several methods in mmdetection or mmsegmentation library which is behind otx

Not able to train segmentation or object detection models. Have tried the fixes suggested in this [link](https://github.com/open-mmlab/mmdetection/issues/7788) and this [link](https://github.com/open-mmlab/mmdetection/issues/6765) but the issue was not solved.  

We want to fix these errors to train a segmentation model. 

![image](https://github.com/openvinotoolkit/training_extensions/assets/37284248/95093d4a-638d-4944-a0a5-6d178e0588b0)

![image](https://github.com/openvinotoolkit/training_extensions/assets/37284248/116256c5-a76f-4e90-8565-e3e46e15fd01)

**Steps to Reproduce**

1. Install OpenVINO™ Training Extensions by using Docker
2. otx build --task instance_segmentation
3. otx train --train-data-roots ../data/wgisd --val-data-roots ../data/wgisd

**Environment:**

- OS: Linux Ubuntu 20.04
- Framework version: PyTorch 1.13.1+cu117
- Python version: 3.10.9
- OpenVINO version: 
- CUDA/cuDNN version: V11.7.99
- GPU model and memory: NVIDIA GeForce GTX 1650 Ti

**Comment by jaegukhyun** [comment]
In my environment, this kind of bug cannot be reproduced. I think we need more information about your env. 
1. How you install otx inside of your docker? 
2. What version of otx you use

**Comment by yunchu** [comment]
@jaegukhyun I guess the answer of the question 1 would be related with Dockerfile in the repo. https://github.com/openvinotoolkit/training_extensions/blob/develop/Dockerfile

**Comment by bismillahkani** [comment]
> In my environment, this kind of bug cannot be reproduced. I think we need more information about your env.
> 
> 1. How you install otx inside of your docker?
> 2. What version of otx you use

otx in installed in docker by this command `pip install --no-cache-dir -e .[full]` 
I cannot get the otx version inside docker.. what is the command to get the version

Can you explain how did you install otx?

**Comment by jaegukhyun** [comment]
@bismillahkani Did you run dockerfile we provided? If so the docker file is for cpu build, that's the reason of cuda error.
If you want to use gpu, please refer our installation guide

**Comment by bismillahkani** [comment]
> @bismillahkani Did you run dockerfile we provided? If so the docker file is for cpu build, that's the reason of cuda error. If you want to use gpu, please refer our installation guide

@jaegukhyun Thanks for your reply. We tried to install otx following the installation guide in WSL-Ubuntu and AWS Sagemaker (CentOS) but the installation failed. The docker installation was successful but cuda issue occurred.

**Comment by jaegukhyun** [comment]
@bismillahkani Could you share error message during installation? And if docker build is more stable, I'd like to recommend to use pytorch nvidia docker(https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch). Note that you should use nvidia docker, not base docker if you want to use gpu for training or inference. If pytorch nvidia docker works in your environment, install above nvidia docekr through installation guide will work.

**Comment by bismillahkani-bh** [comment]
@jaegukhyun we were able install otx on a different linux machine and train a model. Thanks for your support.

**Comment by jaegukhyun** [comment]
Good news!
