### ISSUE TITLE
There are some wrong links in documentation.

### ISSUE THREAD

**Issue by sungchul1** [open-edge-platform/training_extensions#2353]
**Describe the bug**

For example, https://github.com/openvinotoolkit/training_extensions/blob/develop/docs/source/guide/explanation/algorithms/segmentation/semantic_segmentation.rst?plain=1#L45
It seems to be updated.

**Steps to Reproduce**

1.
2.
3.
4.

**Environment:**

- OS: 
- Framework version: 
- Python version:
- OpenVINO version:
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by sungmanc** [comment]
Solved at PR above
