### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" . Inference getting aborted for Instance Segmentation.

### ISSUE THREAD

**Issue by VishwaBhushanBH** [open-edge-platform/training_extensions#2376]
**Instance segmentation inference in AWS Sage Maker is getting aborted.**

**Command** - 
otx demo --input docs/utils/images/wgisd_dataset_sample.jpg --load-weights outputs/weights.pth --output resulted_images

**Error:**
""
[                                                  ] 0/1, elapsed: 0s, ETA:INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1/1, 0.6 task/s, elapsed: 2s, ETA:     0s2023-07-19 08:58:30,514 | INFO : Inference completed
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ec2-user/SageMaker/Segmentation_OpenVino/training_extensions/.otx/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, minimal, minimalegl, offscreen, vnc, webgl.

Aborted
""

It is not saving the inference in the directory. I am good if we can save the inference in a directory and not visually see the results in a seperate window.
There is a similar issue [here](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Openvino-Runtime/m-p/1440355/highlight/true).
I am not able to run inferencing after training the model using OTX because of this.

**Steps to Reproduce**

1. In AWS Sage Maker install OTX following [this](https://openvinotoolkit.github.io/training_extensions/latest/guide/tutorials/base/how_to_train/instance_segmentation.html)
2. Create dataset and train the model following the above link.
3. Run inferencing following this [link](https://openvinotoolkit.github.io/training_extensions/latest/guide/tutorials/base/demo.html)

**Environment:**

- OS: 
- Framework version: 
- Python version:3.10
- CUDA/cuDNN version: 12.0

![image](https://github.com/openvinotoolkit/training_extensions/assets/102714932/2b41abd7-a7aa-4129-9f77-3612f4f3685a)

**Comment by sovrasov** [comment]
To disable visualization, you could pass a negative delay value via command line: `--delay -1`

**Comment by VishwaBhushanBH** [comment]
Thanks @sovrasov for the answer, it worked.
