### ISSUE TITLE
How to Train Open_ Model_ Zoom/models/intel  /Road segmentation adas 0001/This model?

### ISSUE THREAD

**Issue by ZJDATY** [open-edge-platform/training_extensions#2431]
I saw that the model road segmentation adas 0001 only has over 700 KB, and I want to transfer and train others, but I haven't seen any training tutorials for this model. Is it official that it is not open?

https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/road-segmentation-adas-0001

https://storage.openvinotoolkit.org/repositories/open_model_zoo/2023.0/models_bin/1/road-segmentation-adas-0001/FP32/

**Comment by goodsong81** [comment]
Hi, I'm sorry to say that the OTX (OpenVINO Training Extension) does not directly support retraining of models in OMZ (OpenVINO Model Zoo).
You might be able to get information about the source model training from https://github.com/openvinotoolkit/open_model_zoo/issues
