### ISSUE TITLE
Need to fix saliency map merging

### ISSUE THREAD

**Issue by sungmanc** [open-edge-platform/training_extensions#2434]
**Describe the bug**

Will be resolved at the next release of ModelAPI

**Steps to Reproduce**

1. XAI e2e test

**Comment by yunchu** [comment]
this [PR](https://github.com/openvinotoolkit/model_api/pull/122) will fix this issue but not released yet.

**Comment by sungmanc** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/2511 was merged
