### ISSUE TITLE
[suggestion] Could not find module 'geos_c.dll'

### ISSUE THREAD

**Issue by leo-smi** [open-edge-platform/training_extensions#2523]
**Describe the bug**

```Could not find module 'geos_c.dll'```

**Steps to Reproduce**

1. running the step [```pip install -e .[full]```](https://openvinotoolkit.github.io/training_extensions/latest/guide/get_started/installation.html) leads to the problem

**Environment:**

- OS: Windows 10
- Python version: 3.10
- GPU model and memory: Intel Iris Xe

**Solution:**

[```pip uninstall shapely```](https://stackoverflow.com/questions/65345213/could-not-find-module-or-one-of-its-dependencies-try-using-the-full-path-with)
[```conda install shapely```](https://stackoverflow.com/questions/65345213/could-not-find-module-or-one-of-its-dependencies-try-using-the-full-path-with)
run ```pip install -e .[full] --user``` (with the --user flag)

**Comment by sungmanc** [comment]
Thanks for the suggestion and error reporting. @goodsong81  could you check?

**Comment by leo-smi** [comment]
> Thanks for the suggestion and error reporting. @goodsong81 could you check?

I was trying running with the flag --user in python venv (local environment) instead of conda and its not possible to use it, only in the global environment.

**Comment by leo-smi** [comment]
another solution is running:

```pip install mmcv-full==1.7.1```
