### ISSUE TITLE
Too long data time for YOLOX-L model

### ISSUE THREAD

**Issue by sungmanc** [open-edge-platform/training_extensions#2525]
**Describe the bug**

When we used PCD-COCO dataset, the data_time showed consumed too much time than the Ultratics.
<img width="581" alt="image" src="https://github.com/openvinotoolkit/training_extensions/assets/80735344/4a8bceec-3a69-415f-bdd7-7016a7b7b7f4">

Originally reported from @vinnamkim 

**Steps to Reproduce**

1. Training YOLOX-L model by using PCD-COCO dataset

**Comment by goodsong81** [comment]
Not reproduced on the exact same environment of the original reporter.
Data loading is running well in expected speed.

* Environment: ikvensx012 server
  - CPU: Intel(R) Xeon(R) Gold 5320 CPU @ 2.20GHz
  - GPU: NVIDIA A100 80GB PCIe
* How to reproduce
```bash
git checkout develop  # 6b8729a33
tox devenv -e unittest-all-py310-pt1 .venv
source .venv/160/bin/activate
otx train YOLOX-L --train-data-roots /storageserver/pvd_data/otx_data_archive/research_datasets/detection/pcd_coco/ --val-data-roots /storageserver/pvd_data/otx_data_archive/research_datasets/detection/pcd_coco/ --workspace ./pcd_coco_yolox_l_nfs
```
![image](https://github.com/openvinotoolkit/training_extensions/assets/4629606/9c9ac5bd-9389-4c67-9228-36daec1f4bed)

Please reopen this issue if any reproduction is observed.
Thanks!
