### ISSUE TITLE
Which dataset the person reidentification model trained on?

### ISSUE THREAD

**Issue by dangnh0611** [open-edge-platform/training_extensions#2526]
I'm checking the old [misc branch](https://github.com/openvinotoolkit/training_extensions/tree/misc/misc/pytorch_toolkit/object_reidentification/person_reidentification) with person-reidentification code.
Which dataset was used to train these `retail` models ? For example `person-reidentification-retail-0265`, the configuration file [person-reidentification-retail-0265.yaml](https://github.com/openvinotoolkit/training_extensions/blob/misc/misc/pytorch_toolkit/object_reidentification/person_reidentification/configs/person-reidentification-retail-0265.yaml) show that it's trained with MSMT17-all (`combineall=True`) and test on Market-1501. However, the top-1 and mAP seem too high to my knownledge and as mentioned in the corresponding [paper](https://arxiv.org/abs/2003.07618).
Finally, have you released the trained models (weights) in the paper (especially those were trained on MSMT17-all) ?

Thanks !

**Comment by sovrasov** [comment]
Hi
We used more data to train the final model, but it's private, so we cant share the actual dataset. 
Some of the final weights can be found in https://storage.openvinotoolkit.org/repositories/openvino_training_extensions/models/person_reidentification/
Corresponding configs are here: https://github.com/openvinotoolkit/training_extensions/tree/4e8ec5d8d7527b0afa5d506ff1bd35299717262d/pytorch_toolkit/object_reidentification/person_reidentification
