### ISSUE TITLE
Bug during RGB converting in data pipeline

### ISSUE THREAD

**Issue by wonjuleee** [open-edge-platform/training_extensions#2584]
**Describe the bug**

When creating `Image` from datumato media, the media has been already converted to RGB as described in both cases
1. `Image` from path: https://github.com/openvinotoolkit/training_extensions/blob/b4fcc6d055c27792d4769ee1ee343eb2b9bfea7e/src/otx/api/entities/image.py#L94
2. `Image` from data: https://github.com/openvinotoolkit/training_extensions/blob/b4fcc6d055c27792d4769ee1ee343eb2b9bfea7e/src/otx/core/data/adapter/base_dataset_adapter.py#L412

But this has been again converted to RGB in data pipeline, for instances, in classification tasks: https://github.com/openvinotoolkit/training_extensions/blob/b4fcc6d055c27792d4769ee1ee343eb2b9bfea7e/src/otx/algorithms/classification/configs/base/data/data_pipeline.py#L8

As a result, there are some performance drop with current data pipelines..
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

to_rgb | True (as-is) | False (to-be)
-- | -- | --
CIFAR100 (#2500   training data) | Acc: 0.423 / E2E time: 120.16   sec | Acc: 0.473 / E2E time: 159.17 sec
CUB200 (#1200   training data) | Acc: 0.615 / E2E time: 41.27   sec | Acc: 0.680 / E2E time: 41.92 sec

</div>

</body>

</html>

**Steps to Reproduce**

1. Turn `to_rgb=False`
2. Do experiments

**Environment:**

- OS: Ubuntu 20.04
- Framework version: PyTorch 2.0
- Python version: Python 3.10
- OpenVINO version:
- CUDA/cuDNN version: 11.7
- GPU model and memory: RTX3090

**Comment by sovrasov** [comment]
If datumaro image is the only source of images in OTX train, we have to make similar changes in all our components. As far as I understand, this change won't affect pytorch models, so we don't have to change OV-related things.

**Comment by sungmanc** [comment]
Thanks for the reporting, I attached the reason of this issue and made a PR for that.

**Comment by goodsong81** [comment]
@sungmanc Can we close this issue by https://github.com/openvinotoolkit/training_extensions/pull/2585 ?

**Comment by sungmanc** [comment]
> @sungmanc Can we close this issue by #2585 ?

Ah, thanks.
