### ISSUE TITLE
Typo on model_template_id of EfficientNet-B0

### ISSUE THREAD

**Issue by wonjuleee** [open-edge-platform/training_extensions#2592]
**Describe the bug**

The model_template_id of EfficientNet-B0 is wrong

https://github.com/openvinotoolkit/training_extensions/blob/ead81401bb9024b6370716965885228870871230/src/otx/algorithms/classification/configs/efficientnet_b0_cls_incr/template.yaml#L2C19-L2C63

The name should be `Custom_Image_Classification_EfficientNet-B0`.
 

**Steps to Reproduce**

1.
3.
4.
5.

**Environment:**

- OS: 
- Framework version: 
- Python version:
- OpenVINO version:
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by Asymtode712** [comment]
I want to fix this issue please assign me

**Comment by wonjuleee** [comment]
> I want to fix this issue please assign me

Thank you for your interests! But, sorry that this is strongly related to our another commercial product and it might be good to fix by our internal developer.

**Comment by wonjuleee** [comment]
@jaegukhyun, could you fix this when you are available?
