### ISSUE TITLE
IndexError while NNCF optimization regression testing with YOLOX-S template for the detection along with tiling

### ISSUE THREAD

**Issue by yunchu** [open-edge-platform/training_extensions#2596]
**Describe the bug**

tested on branch `releases/1.5.0`

IndexError while NNCF optimization regression testing with YOLOX-S template for the detection along with tiling

![image](https://github.com/openvinotoolkit/training_extensions/assets/5232387/2ecaff90-d93f-4a06-bcf4-ed533333f9af)

**Steps to Reproduce**

1. copy datasets for the regression test
2. run regression test
```
$ CI_DATA_ROOT=/home/yunchule/data/ci_datasets/ tox -vvv -e tests-det-py310-pt1 -- tests/regression/detection/ -k "Object_Detection_YOLOX_S"
```

**Environment:**

- OS: Ubuntu-20.04
- Framework version: PyTorch
- Python version: 3.10
- OpenVINO version: 2023.0
- CUDA/cuDNN version: 11.7
- GPU model and memory: 3090

**Comment by goodsong81** [comment]
Disabled NNCF optimization (QAT) for YOLOX-S.
https://github.com/openvinotoolkit/training_extensions/pull/2636
