### ISSUE TITLE
Multi-GPU training integration test failure

### ISSUE THREAD

**Issue by sovrasov** [open-edge-platform/training_extensions#2705]
The failure occurs in daily tests for at least a week in a row :
https://github.com/openvinotoolkit/training_extensions/actions/runs/7105336612
FAILED tests/e2e/cli/detection/test_detection.py::TestToolsOTXSemiSLDetection::test_otx_multi_gpu_train_semisl[Object_Detection_ResNeXt101_ATSS]

@eunwoosh could you have a look?

**Comment by eunwoosh** [comment]
Sure I'll take a look.
