### ISSUE TITLE
No evaluation metric outputs for Anomaly exported & optimized models

### ISSUE THREAD

**Issue by goodsong81** [open-edge-platform/training_extensions#3154]
Train -> Test gives following output:
![image](https://github.com/openvinotoolkit/training_extensions/assets/4629606/5193ff23-6659-486c-8c7f-592b4ffafbb6)

But, Export or Optimize -> Test gives no evaluation metrics:
![image](https://github.com/openvinotoolkit/training_extensions/assets/4629606/3ed74957-fbff-41a5-84c6-0bf66a8f5d7b)
And even seems like testing wrong data subset; 237 images, not 8.

**How to reproduce**
On the latest develop (v2.0)
(Any datasets would reproduce the above results)
```console
otx train --config src/otx/recipe/anomaly_classification/stfpm.yaml --data_root /mnt/sdc/otx_v2_dataset/anomaly/mvtec/wood_medium --work_dir /tmp/pytest-of-songkich/pytest-7/otx-benchmark0/20240319-105856/anomaly_classification/stfpm/mvtec_wood_medium/0 --model.num_classes 2 --data.config.data_format mvtec --engine.device gpu --seed 0 --deterministic False
otx test --work_dir /tmp/pytest-of-songkich/pytest-7/otx-benchmark0/20240319-105856/anomaly_classification/stfpm/mvtec_wood_medium/0
otx export --work_dir /tmp/pytest-of-songkich/pytest-7/otx-benchmark0/20240319-105856/anomaly_classification/stfpm/mvtec_wood_medium/0
otx test --config src/otx/recipe/anomaly_classification/openvino_model.yaml --checkpoint /tmp/pytest-of-songkich/pytest-7/otx-benchmark0/20240319-105856/anomaly_classification/stfpm/mvtec_wood_medium/0/.latest/export/exported_model.xml --work_dir /tmp/pytest-of-songkich/pytest-7/otx-benchmark0/20240319-105856/anomaly_classification/stfpm/mvtec_wood_medium/0
```

**Comment by harimkang** [comment]
@ashwinvaidya17 Can you take a look at this? As I understand it, the metrics on the `AnomalyModule` side are internal and not configured separately in OTX.

**Comment by goodsong81** [comment]
@ashwinvaidya17 Could you check the right metrics for each task?
Currently, Train -> Test outputs
* Anomaly classification
  - image_F1Score/AUROC
* Anomaly detection
  - image_F1Score/AUROC
  - pixel_F1Score/AUROC
* Anomaly segmentation
  - image_F1Score/AUROC
  - pixel_F1Score/AUROC

Which one is the representative for each task?
As I remember, it was mDice for the anomaly segmentation task in OTX1.x.

**Comment by ashwinvaidya17** [comment]
Yeah, I'll have a look at the test metrics. I didn't add any other metrics on top of the ones used in Anomalib. So I think even the detection metric is different from the v1 task. But since the plan is to remove anomaly detection in Geti, I'll see which metric is more appropriate.
