### ISSUE TITLE
E2E test failures while train instance segmentation models

### ISSUE THREAD

**Issue by yunchu** [open-edge-platform/training_extensions#3276]
**Describe the bug**

FAILED tests/e2e/cli/test_cli.py::test_otx_e2e_cli[gpu-instance_segmentation/maskrcnn_r50_tile.yaml]
FAILED tests/e2e/cli/test_cli.py::test_otx_e2e_cli[gpu-instance_segmentation/maskrcnn_swint_tile.yaml]
FAILED tests/e2e/cli/test_cli.py::test_otx_e2e_cli[gpu-instance_segmentation/maskrcnn_efficientnetb2b_tile.yaml]
FAILED tests/e2e/cli/test_cli.py::test_otx_e2e_cli[gpu-instance_segmentation/rtmdet_inst_tiny_tile.yaml]

```
packages/datumaro/plugins/tiling/tile.py", line 81, in _tile_polygon
    points=[p for xy in inter.exterior.coords for p in xy], attributes=deepcopy(ann.attributes)
AttributeError: 'GeometryCollection' object has no attribute 'exterior'
```

**Steps to Reproduce**

1. prepare e2e datasets
2. CI_DATA_ROOT=<path-to-e2e-dataset-root> tox -e e2e-test-instance_segmentation -- -k test_otx_e2e_cli
3. check results
https://github.com/openvinotoolkit/training_extensions/actions/runs/8563639340/job/23468967867

**Comment by eugene123tw** [comment]
PR created: https://github.com/openvinotoolkit/training_extensions/pull/3283/files

**Comment by eugene123tw** [comment]
fixed: https://github.com/openvinotoolkit/training_extensions/actions/runs/8610962362/job/23597313656
