### ISSUE TITLE
E2E test failures on anomaly task

### ISSUE THREAD

**Issue by yunchu** [open-edge-platform/training_extensions#3277]
**Describe the bug**

FAILED tests/e2e/cli/test_cli.py::test_otx_e2e_cli[gpu-anomaly_classification/draem.yaml]
FAILED tests/e2e/cli/test_cli.py::test_otx_hpo_e2e_cli[gpu-ANOMALY_DETECTION]
FAILED tests/e2e/cli/test_cli.py::test_otx_hpo_e2e_cli[gpu-ANOMALY_SEGMENTATION]

**Steps to Reproduce**

1. prepare e2e dataset
2. CI_DATA_ROOT=<path-to-e2e-dataset-root> tox -e e2e-test-anomaly
3.check result
https://github.com/openvinotoolkit/training_extensions/actions/runs/8563639340/job/23468967060

**Comment by chuneuny-emily** [comment]
@ashwinvaidya17 - Can you give me an ETA on when this issue can be fixed?

**Comment by ashwinvaidya17** [comment]
@chuneuny-emily I guess it should work once the PR is merged

**Comment by chuneuny-emily** [comment]
closed not reproduced now.
