### ISSUE TITLE
Slowness issues with np array based transform (otx.core.data.transform_libs.torchvision.Resize)

### ISSUE THREAD

**Issue by harimkang** [open-edge-platform/training_extensions#3379]
**Describe the bug**

Despite importing MM's implementation into transform for resolving slowness issue (https://github.com/openvinotoolkit/training_extensions/pull/3253), 
the inefficient process of `np array -> tv_image -> np array` results in the following differences.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

MULTI_CLASS_CLS | val/iter_time
-- | --
mm.Resize (np.array) | 0.174
Torchvision.v2.Resize (tv.Image) | 0.240
otx.Resize   (tv_image -> np.array) | 0.231
otx.Resize   without converting to tv.Image (np.array) | 0.173

</div>

</body>

</html>

torchvision transfrom always use tv_image: https://github.com/openvinotoolkit/training_extensions/blob/03884711f2aa1ac02512ad6f6beb0a721366a4c8/src/otx/core/data/dataset/base.py#L96

But, New `otx.Resize` based np.array: https://github.com/openvinotoolkit/training_extensions/blob/03884711f2aa1ac02512ad6f6beb0a721366a4c8/src/otx/core/data/transform_libs/torchvision.py#L494
https://github.com/openvinotoolkit/training_extensions/blob/03884711f2aa1ac02512ad6f6beb0a721366a4c8/src/otx/core/data/transform_libs/torchvision.py#L504

In my personal opinion, the best thing to do would be to improve torchvision.v2.Resize based on tv Image.
But I'm not sure how to do that right now

**Steps to Reproduce**

1.
2.
3.
4.

**Environment:**

- OS: 
- Framework version: 
- Python version:
- OpenVINO version:
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by sungchul1** [comment]
Currently, `otx.Resize` supports only numpy image because it uses `cv2.resize`.
The best thing I think is setting an option whether to convert an image in entity to `tv_tensors.Image` when starting transforms or not, and converting the image to `tv_tensors.Image` after transforms are finished if the image is still numpy.
https://github.com/openvinotoolkit/training_extensions/blob/7ba7c15ce3de89eb83e37cd72f9044403bb0cb85/src/otx/core/data/dataset/base.py#L95-L97

**Comment by sungchul1** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/3418

**Comment by sovrasov** [comment]
FYI, here is the comparison between resize types we use. Torchvision and OpenCV resize are compared against OV resize. That information could be useful for understanding the influence of the resize method we use on inference reproducibility.

![image](https://github.com/openvinotoolkit/training_extensions/assets/5373517/405173b5-b082-4376-af0a-bd4088bdc7c9)
