### ISSUE TITLE
Anomaly task training performance degradation for v2.0.0

### ISSUE THREAD

**Issue by yunchu** [open-edge-platform/training_extensions#3592]
Anomaly tasks in OTX2.0.0 show performance degradation compared to OTX1.5.2.

How to run the anomaly benchmark tests

```bash
pytest -vs tests/perf/test_anomaly.py --output-root benchmark_result --model-category all --data-root /path/to/val-data/v1 --eval-upto train --num-repeat 5 
```
![image-2024-04-09-16-28-24-336](https://github.com/openvinotoolkit/training_extensions/assets/5232387/912093ee-cf8a-4078-b0d2-baa88c982688)

**Comment by chuneuny-emily** [comment]
@ashwinvaidya17 - Please check about e2e time degradation.
