### ISSUE TITLE
Accuracy drop on Post-Training Quantization (PTQ) optimized model for maskrcnn-swimt

### ISSUE THREAD

**Issue by yunchu** [open-edge-platform/training_extensions#3593]
Post-Training Quantization (PTQ) optimization applied to `maskrcnn_swimt` in the instance segmentation task may result in significantly reduced accuracy.

How to run the ins_seg benchmark tests for OTX 2.0.0

```bash
pytest -vs tests/perf/test_instance_segmentation.py --output-root benchmark_otx_2.0.0_result --model-category all --data-root /path/to/val-data/v2 --eval-upto optimize --num-repeat 5 
```

![image-2024-06-05-16-29-29-929](https://github.com/openvinotoolkit/training_extensions/assets/5232387/aea78b39-fa06-42a5-a58d-bea3f1741c0d)

**Comment by chuneuny-emily** [comment]
cc'ed @eugene123tw

**Comment by eugene123tw** [comment]
Fixed in https://github.com/openvinotoolkit/training_extensions/pull/3685

**Comment by chuneuny-emily** [comment]
This issue is expected to be addressed with an upgrade to OpenVINO and NNCF in a future release.

**Comment by sovrasov** [comment]
Fixed in https://github.com/openvinotoolkit/training_extensions/pull/3900
