### ISSUE TITLE
Is this only for pytorch 2.1.1？

### ISSUE THREAD

**Issue by chunhuanMeng** [open-edge-platform/training_extensions#3766]
Is this only for pytorch 2.1.1？

**Comment by harimkang** [comment]
@chunhuanMeng Currently we don't have a wide range of torch versions to test, so we can't be specific, but the current validated torch is 2.1.1.
Is there a specific version you're looking for?

**Comment by chunhuanMeng** [comment]
yes, I wanna try pytorch 2.3.1

**Comment by harimkang** [comment]
@chunhuanMeng 
I tested it on a simple classification task.
Here's how I set it up

```shell
# Ubuntu 22.04 & GTX 3090
pip install -e '.[base]' # pip install otx[base]
pip install torch==2.3.1
```

When I tested with the above environment, works with this changes: https://github.com/openvinotoolkit/training_extensions/pull/3775

This works, but it's not official, not fully-validated (for now), and may have unintended issues. Please note

**Comment by harimkang** [comment]
Merge related PR https://github.com/openvinotoolkit/training_extensions/pull/3775 to develop.

**Comment by harimkang** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/3843 - For now, we've updated to torch 2.4 as of the develop branch, so closing this issue.
