### ISSUE TITLE
Issue: RTDETR Accuracy Regression in `develop` branch

### ISSUE THREAD

**Issue by eugene123tw** [open-edge-platform/training_extensions#4109]
**Describe the bug**

RTDETR has regressed, with all variants currently showing 0% accuracy on the current develop branch (c3da87659a).

**Steps to Reproduce**

`git checkout develop`

`otx train --config src/otx/recipe/detection/rtdetr_18.yaml --data_root pothole_medium --max_epochs 20`

**Environment:**

- OS: 
- Framework version: 
- Python version:
- OpenVINO version:
- CUDA/cuDNN version:
- GPU model and memory:

| **Train Metric**          | **Value**                          |
|---------------------------|------------------------------------|
| val/map                   | 0.0                                |
| val/map_50                | 0.0                                |
| val/map_75                | 0.0                                |
| val/map_small             | 0.0                                |
| val/map_medium            | 0.0                                |
| val/map_large             | 0.0                                |
| val/mar_1                 | 0.0                                |
| val/mar_10                | 0.0                                |
| val/mar_100               | 0.0                                |
| val/mar_small             | 0.0                                |
| val/mar_medium            | 0.0                                |
| val/mar_large             | 0.0                                |
| val/map_per_class         | -1.0                               |
| val/mar_100_per_class     | -1.0                               |
| val/classes               | 0.0                                |
| val/f1-score              | 0.0                                |
| train/data_time           | 0.010923218913376331              |
| train/iter_time           | 0.2313225269317627                |

**Comment by sovrasov** [comment]
@eugene123tw will https://github.com/openvinotoolkit/training_extensions/pull/4102 solve the issue? I had an impression it contains the related changes in augmentations

**Comment by eugene123tw** [comment]
@sovrasov I'm running benchmark on https://github.com/openvinotoolkit/training_extensions/pull/4098. So far so good. I will close this issue once the benchmark is complete.

**Comment by eugene123tw** [comment]
Accuracy issue fixed in #4098

**Comment by eugene123tw** [comment]
Accuracy issue fixed in https://github.com/openvinotoolkit/training_extensions/pull/4098
