### ISSUE TITLE
ONNX dynamic shaping error in OpenCV embedding shape interpolate

### ISSUE THREAD

**Issue by eugene123tw** [open-edge-platform/training_extensions#4111]
**Describe the bug**
ONNX dynamic shaping not working with Model API `inference_adapter.embed_preprocessing`.

```
[CPU] Interpolate node with name 'Interpolate_65093' Check 'cmp::le(m_min, u) && cmp::le(u, m_max)' failed at src/core/shape_inference/include/shape_infer_type_utils.hpp:54:
Value -1 not in range [0:18446744073709551615]
```

**Steps to Reproduce**

1. `otx train --config src/otx/recipe/detection/atss_mobilenetv2.yaml --data_root tests/assets/car_tree_bug --work_dir otx-workspace/atss_mobilenetv2 `
2. `otx export  --work_dir otx-workspace/atss_mobilenetv2 --export_format ONNX`
3. ` otx test --work_dir otx-workspace/atss_mobilenetv2  --checkpoint otx-workspace/atss_mobilenetv2/.latest/export/exported_model.onnx`

**Environment:**

- OS: 
- Framework version: 
- Python version:
- OpenVINO version:
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by sovrasov** [comment]
@eugene123tw feel free to remove all the related dynamic h w setting in onnx configurations: detection, instance segmentation and keypoint detection are affected
