### ISSUE TITLE
Is there a way to retain model "license-plate-recognition-barrier-0001" for other countries

### ISSUE THREAD

**Issue by IvanZhangDoIt** [open-edge-platform/training_extensions#600]
**Is your feature request related to a problem? Please describe.**

**Comment by morkovka1337** [comment]
Hi.

You can try to retrain the LPR using the code you have mentioned above, convert the trained model to the OpenVINO IR and then you can work with it using the DLStreamer. 
The other option is to use the [text-recognition training code](https://github.com/openvinotoolkit/training_extensions/tree/develop/misc/pytorch_toolkit/text_recognition). The text-recognition-0014 should suit well for this task, it is fast and easy to convert to ONNX & IR.

**Comment by morkovka1337** [comment]
Closing this due to the lack of activity. If you have any other questions, feel free to reopen or create new issue.
