### ISSUE TITLE
Training Person Attribute Recognition on custom Dataset.

### ISSUE THREAD

**Issue by navyverma** [open-edge-platform/training_extensions#773]
I want to train Person attribute Recognition on a custom dataset. 
[https://docs.openvino.ai/2019_R1/_person_attributes_recognition_crossroad_0230_description_person_attributes_recognition_crossroad_0230.html]()
This is the link to the model info. It takes the input of person image and provides pre-defined attributes of that person.
Can I train this model using this training_extension repo?

**Comment by morkovka1337** [comment]
Hi,

Unfortunately, we cannot provide code for training person attributes model. All we can offer you is similar model for vehicle attributes: https://github.com/openvinotoolkit/training_extensions/tree/master/misc/tensorflow_toolkit/vehicle_attributes. 
**Note**: this code is not officially supported now and provided as is. Correct work of it is not guaranteed.

If you have your own dataset, I think, with small changes you can adapt this code to train the model.

**Comment by navyverma** [comment]
@morkovka1337 Thank you, for the response. I'll check this link.
