### ISSUE TITLE
Checkpoint files for custom object detector is not available

### ISSUE THREAD

**Issue by dtoya** [open-edge-platform/training_extensions#846]
Hello,

I could not fined checkpoint files for custom object detection models on the following page. 

https://github.com/openvinotoolkit/mmdetection/tree/825488ada5e07f8461c991ab37578bab5eedf423/configs/ote/custom-object-detection

In case of other model like face detection, checkpoint files are linked on the similar readme page as follows. 
https://github.com/openvinotoolkit/mmdetection/tree/825488ada5e07f8461c991ab37578bab5eedf423/configs/ote/face-detection

Could you please add links to checkpoint files for custom object detector?

Best Regards,
Toya

**Comment by druzhkov-paul** [comment]
Hello Toya.

Thanks for bringing this up. Those readme files to be updated soon. As for custom object detection, path to the checkpoint is now a part of [model config itself](https://github.com/openvinotoolkit/mmdetection/blob/ote/configs/ote/custom-object-detection/gen3_mobilenetV2_ATSS/model.py#L87) and it is downloaded automatically during model initialization. But please note that provided checkpoints for custom object detectors are just the starting points for fine-tuning on a target dataset, not the final weights.

**Comment by dtoya** [comment]
Thank you! I understand it. I will close this ticket.
