### ISSUE TITLE
No module named 'openvino.runtime'

### ISSUE THREAD

**Issue by XinyuDu** [open-edge-platform/training_extensions#879]
get error <No module named 'openvino.runtime'> when run this script:
```
python ${OMZ_DIR}/demos/text_spotting_demo/python/text_spotting_demo.py \
   -m_m export/model.xml \
   -m_te export/model_text_recognition_head_encoder.xml \
   -m_td export/model_text_recognition_head_decoder.xml \
   -i /dev/video0
```

**Comment by morkovka1337** [comment]
Hi, @XinyuDu 

What version of OpenVINO do you use and what branch of the OMZ are you in? Note that `master` branch of omz relies on the new layout of the OpenVINO and requires OpenVINO `2022.1`. If you do not want to change the version of OpenVINO, you can switch to the `releases/2021/4` branch (1 or 2 depending on which version of OpenVINO you have).

**Comment by XinyuDu** [comment]
> Hi, @XinyuDu
> 
> What version of OpenVINO do you use and what branch of the OMZ are you in? Note that `master` branch of omz relies on the new layout of the OpenVINO and requires OpenVINO `2022.1`. If you do not want to change the version of OpenVINO, you can switch to the `releases/2021/4` branch (1 or 2 depending on which version of OpenVINO you have).

OK, thx.
