### ISSUE TITLE
ModuleNotFoundError: No module named '_pyngraph'

### ISSUE THREAD

**Issue by Praveen-mvp** [open-edge-platform/training_extensions#945]
Received a error While running the Object-detection-python demo

![er](https://user-images.githubusercontent.com/78363617/155270425-1d00b91b-3c0c-45fe-b1ea-306c9798744f.jpg)

**Comment by vladimir-dudnik** [comment]
@Praveen-mvp Open Model Zoo released and validated with each OpenVINO public release. So it depends on this particular OpenVINO release features and have to be used with it.
It's not clear where you took Open Model Zoo demo from, it looks like you use OMZ from OTE as submodule and not from OpenVINO release? If so, than you better to ask at OTE github what version of OMZ they use as OTE submodule and what OpenVINO version it is compatible with.

**Comment by druzhkov-paul** [comment]
@Praveen-mvp please provide more information following the template for issues in this repo.
